language: php

php:
  - 5.2
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.2

script: 
    - phpunit -c phpunit.xml
    - tools/phptal_lint.php -e html tests/input/phptal*.html